### ISSUE TITLE
Allow for user deletion.

### ISSUE THREAD

**Issue by pedramamini** [InQuest/ThreatKB#244]

**Comment by pedramamini** [comment]
Works for some, but not for others. Try deleting the ‘stephen’ account for example.

**Comment by danny248** [comment]
This is fixed now. There were some foreign key constraints failing. I changed it to a soft delete of users since hard deletes would involve a lot of artifact re-assignments for created_by, modified_by, ownership, etc.

**Comment by pedramamini** [comment]
Still not seeing this working. Now the deleted users appear with a ghosted out deletion icon.

**Comment by danny248** [comment]
This is intended. We can't hard delete users because they are tied to artifacts ownership, modified, created, etc.

**Comment by pedramamini** [comment]
In that case. If it's trivial enough, let's break the users list into two sections. Active and inactive.
